export const Permission = {
  CREATE_REQUEST: 'CREATE_REQUEST',
  EXECUTE_BATCH: 'EXECUTE_BATCH',
  APPROVE_LEVEL_1: 'APPROVE_LEVEL_1',
  APPROVE_LEVEL_2: 'APPROVE_LEVEL_2',
  TRIGGER_STOPPER: 'TRIGGER_STOPPER',
  CLEAR_STOPPER: 'CLEAR_STOPPER',
};
