export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CREATOR: 'CREATOR',
  FLOOR_LEAD: 'FLOOR_LEAD',
  AUDITOR: 'AUDITOR',
  PROD_MGR: 'PROD_MGR',
  PLANT_HEAD: 'PLANT_HEAD',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};
